name: 'salary_survey'
version: 1.0.0
config-version: 2

models:
  SALARY_SURVEY:
    staging:
      +materialized: view
      +on_schema_change: sync_all_columns
    mart:
      +materialized: view
      +on_schema_change: sync_all_columns
