with cleaned_and_renamed as(
select
COALESCE(TRIM("HOW OLD ARE YOU?"), '0') AS age,
COALESCE(TRIM("WHAT IS YOUR GENDER?"), 'Na') as gender,
COALESCE(TRIM("WHAT IS YOUR RACE? (CHOOSE ALL THAT APPLY.)"), 'NA') as race,
COALESCE(TRIM("WHAT IS YOUR HIGHEST LEVEL OF EDUCATION COMPLETED?"), 'Na') as education,
  
COALESCE(TRIM("WHAT CITY DO YOU WORK IN?"), 'Na')  as work_city,
COALESCE(TRIM("IF YOU''RE IN THE U.S., WHAT STATE DO YOU WORK IN?"), 'Na') as work_state,
COALESCE(TRIM("WHAT COUNTRY DO YOU WORK IN?"), 'Na') as work_country,

  
COALESCE(TRIM("WHAT INDUSTRY DO YOU WORK IN?"), 'Worker') as industry,
COALESCE(TRIM ("JOB TITLE"),'Na') as job_title,
COALESCE(TRIM("IF YOUR JOB TITLE NEEDS ADDITIONAL CONTEXT, PLEASE CLARIFY HERE:"), 'Na') as additional_job_title,
  
COALESCE(TRIM("PLEASE INDICATE THE CURRENCY"), '€') as currency,
COALESCE(TRIM("IF ""OTHER,"" PLEASE INDICATE THE CURRENCY HERE:"), 'Other') as other_currency,
COALESCE(TRIM("WHAT IS YOUR ANNUAL SALARY? (YOU''LL INDICATE THE CURRENCY IN A LATER QUESTION. IF YOU ARE PART-TIME OR HOURLY, PLEASE ENTER AN ANNUALIZED EQUIVALENT -- WHAT YOU WOULD EARN IF YOU WORKED THE JOB 40 HOURS A WEEK, 52 WEEKS A YEAR.)"), 'Na') as total_salary,
COALESCE(TRIM("HOW MUCH ADDITIONAL MONETARY COMPENSATION DO YOU GET, IF ANY (FOR EXAMPLE, BONUSES OR OVERTIME IN AN AVERAGE YEAR)? PLEASE ONLY INCLUDE MONETARY COMPENSATION HERE, NOT THE VALUE OF BENEFITS."), 'Na') as compansation,
COALESCE(TRIM("IF YOUR INCOME NEEDS ADDITIONAL CONTEXT, PLEASE PROVIDE IT HERE:"), 'Na') as income_comments,

COALESCE(TRIM("HOW MANY YEARS OF PROFESSIONAL WORK EXPERIENCE DO YOU HAVE OVERALL?"), '0') as total_experience,
COALESCE(TRIM("HOW MANY YEARS OF PROFESSIONAL WORK EXPERIENCE DO YOU HAVE IN YOUR FIELD?"),'Na') as current_field_experience
from {{ source('SOURCE_SALARY_SURVEY', 'SURVEY') }}
)
SELECT * FROM cleaned_and_renamed
